spring.application.name=this-month-be
server.port=57011
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}